const { seedlist, patchlist } = require('./modules/generate');
const Player = require('./modules/player');
/*
function patches(player) {
	//Takes {patchlist} and returns an array of patches 
	//that you can use according to your level.
	let lilpatchlist = []
	for (let num in patchlist) {
		if (patchlist[num].level <= player.level) {
			lilpatchlist.push(patchlist[num].location)
		}
	}
	return lilpatchlist;
}

function stackUp(items) {
	let inv = []
	let returninv = {}

	for (let num in items) {
		inv.push(items[num].split(' x '))
	}

	for (let num in inv) {
		if (returninv[inv[num][0]] === undefined) {
			returninv[inv[num][0]] = parseInt(inv[num][1])
		} else if (returninv[inv[num][0]] === returninv[inv[num][0]]) {
			returninv[inv[num][0]] = returninv[inv[num][0]] + parseInt(inv[num][1])
		}
	}
	console.log(returninv);
}

function getinventory(patches, player) {
	//Takes patches array (probably generated by patches()) and
	//returns items needed based on them and player level.
	let bestseeds = []
	let inventory = []
	for (let num in patches) {
		let patchname = eval(patches[num])
		bestseeds.push(patchname.maxseed(player))
	}
	for (let seed in bestseeds) {
		//3 seeds per allotment
		inventory.push(bestseeds[seed].name + ' seeds x 3')
	}
	inventory = stackUp(inventory)
}

//Create the player #leet boy
const player = new Player(username = 'Jane Solo', level = 32)

console.log(patchlist);
 */

console.log(seedlist);
console.log(patchlist);

//getinventory(patchlist, player);