//these will hold the list of all the patch's and seeds on creation.
//note, seeds need to be initialized first, then patches.
let patchlist = [] //list of all patches
const seedlist = [] //list of all seeds

class Player {
	constructor() {
		//he be a leet boy.
		this.username = username
		this.level = level // should be calling this. and then a method to lookup level.
	}
}

class Seed {
	constructor(name = '', level = 0, xp = 0, type = '') {
		this.name = name;
		this.level = level;
		this.xp = xp;
		this.type = type;
		seedlist.push(this);
	}
}

class Patch {
	constructor(location = '', seeds = [], type = '', location_name = '') {
		this.location = location;
		this.type = type;
		patchlist.push(this);
		this.generateSeeds();
		this.location_name = location_name;

	}

	generateSeeds() {
		let generatedseeds = []
		for (let num in seedlist) {
			if (seedlist[num].type !== this.type) {
			} else if ((seedlist[num].type === this.type) && (this.seeds === undefined)) {
				generatedseeds.push(seedlist[num]);
			} else if ((seedlist[num].type === this.type) && (this.seeds !== undefined)) {
				generatedseeds.push(seedlist[num]);
			}
			this.seeds = generatedseeds
		}
		//console.log(this.location + "'s seed gen")
		//console.log(this.seeds)
	};
	minseed() {
		//this returns the smallest/largest level for the seeds in the patch
		let seedlist = [];
		for (let num in this.seeds) {
			seedlist.push(this.seeds[num].level);
		}
		//console.log((Math.min(...seedlist)));
	}
	maxseed(player) {
		//this returns the smallest/largest level for the seeds in the patch
		let returnseed = Babyseed // Baby seed is a placeholder seed
		for (let num in this.seeds) {
			if ((this.seeds[num].level <= player.level) && 
				(this.seeds[num].level >= returnseed.level)) {
				returnseed = this.seeds[num]
			}
		}
		return(returnseed)
	}

}

function patches(player) {
	//Takes {patchlist} and returns an array of patches 
	//that you can use according to your level.
	let lilpatchlist = []
	for (let num in patchlist) {
		if (patchlist[num].level <= player.level) {
			lilpatchlist.push(patchlist[num].location)
		}
	}
	return lilpatchlist;
}
/*
function splitInfo(item) {
	return(item.split(' x '))
}*/

function stackUp(items) {
	let inv = []
	let returninv = {}

	for (let num in items) {
		inv.push(items[num].split(' x '))
	}

	for (let num in inv) {
		if (returninv[inv[num][0]] === undefined) {
			returninv[inv[num][0]] = parseInt(inv[num][1])
		} else if (returninv[inv[num][0]] === returninv[inv[num][0]]) {
			returninv[inv[num][0]] = returninv[inv[num][0]] + parseInt(inv[num][1])
		}
	}
	console.log(returninv);
}

function getinventory(patches, player) {
	//Takes patches array (probably generated by patches()) and
	//returns items needed based on them and player level.
	let bestseeds = []
	let inventory = []
	for (let num in patches) {
		let patchname = eval(patches[num])
		bestseeds.push(patchname.maxseed(player))
	}
	for (let seed in bestseeds) {
		//3 seeds per allotment
		inventory.push(bestseeds[seed].name + ' seeds x 3')
	}
	inventory = stackUp(inventory)
}

//Define the seeds
const Babyseed = new Seed(name = 'Babyseed', level = 0, xp = 0, type = 'god')
//creating allotments
const Potato = new Seed(name = 'Potato', level = 1, xp = 98, type = 'allotment')
const Onion = new Seed(name = 'Onion', level = 5, xp = 114.5, type = 'allotment')
const Cabbage = new Seed(name = 'Cabbage', level = 7, xp = 125, type = 'allotment')
const Tomato = new Seed(name = 'Tomato', level = 12, xp = 152.5, type = 'allotment')
const Sweetcorn = new Seed(name = 'Sweetcorn', level = 20, xp = 207, type = 'allotment')
const Strawberry = new Seed(name = 'Strawberry', level = 31, xp = 316, type = 'allotment')
const Watermelon = new Seed(name = 'Watermelon', level = 47, xp = 593.5, type = 'allotment')
//creating flowers
const Marigold = new Seed(name = 'Marigold', level = 2, xp = 55.5, type = 'flower')
const Rosemary = new Seed(name = 'Rosemary', level = 11, xp = 78.5, type = 'flower')
const Nasturtium = new Seed(name = 'Nasturtium', level = 24, xp = 130.5, type = 'flower')
const Woad = new Seed(name = 'Woad', level = 25, xp = 136, type = 'flower')
const Limpwurt = new Seed(name = 'Limpwurt', level = 26, xp = 160, type = 'flower')
//creating herbs
const Guam = new Seed(name = 'Guam', level = 9, xp = 98.5, type = 'herb')
const Marrentill = new Seed(name = 'Marrentill', level = 14, xp = 118.5, type = 'herb')
const Tarromin = new Seed(name = 'Tarromin', level = 19, xp = 142, type = 'herb')
const Harralander = new Seed(name = 'Harralander', level = 26, xp = 189.5, type = 'herb')
const Gout = new Seed(name = 'Gout', level = 29, xp = 420, type = 'herb')
const Ranarr = new Seed(name = 'Ranarr', level = 32, xp = 240.5, type = 'herb')
const Toadflax = new Seed(name = 'Toadflax', level = 38, xp = 303.5, type = 'herb')
const Irit = new Seed(name = 'Irit', level = 44, xp = 382.5, type = 'herb')
const Avantoe = new Seed(name = 'Avantoe', level = 50, xp = 485, type = 'herb')
const Kwuarm = new Seed(name = 'Kwuarm', level = 56, xp = 615, type = 'herb')
const Snapdragon = new Seed(name = 'Snapdragon', level = 62, xp = 777, type = 'herb')
const Cadantine = new Seed(name = 'Cadantine', level = 67, xp = 946.5, type = 'herb')
const Lantadyme = new Seed(name = 'Lantadyme', level = 73, xp = 1195, type = 'herb')
const Dwarf = new Seed(name = 'Dwarf', level = 79, xp = 1514.5, type = 'herb')
const Torstol = new Seed(name = 'Torstol', level = 85, xp = 1771, type = 'herb')

//Creating the Patches
//Location 1 (South of Falador)
const L11 = new Patch( location = 'L11', seeds = [], type = 'allotment', location_name = 'South of Falador')
const L12 = new Patch( location = 'L12', seeds = [], type = 'allotment', location_name = 'South of Falador')
const L13 = new Patch( location = 'L13', seeds = [], type = 'flower', location_name = 'South of Falador')
const L14 = new Patch( location = 'L14', seeds = [], type = 'herb', location_name = 'South of Falador')

//Location 2 (West of Port Phasmatys)
const L21 = new Patch(location = 'L21', seeds = [], type = 'allotment', location_name = 'West of Port Phasmatys')
const L22 = new Patch(location = 'L22', seeds = [], type = 'allotment', location_name = 'West of Port Phasmatys')
const L23 = new Patch(location = 'L23', seeds = [], type = 'flower', location_name = 'West of Port Phasmatys')
const L24 = new Patch(location = 'L24', seeds = [], type = 'herb', location_name = 'West of Port Phasmatys')

//Location 3 (North of Catherby)
const L31 = new Patch(location = 'L31', seeds = [], type = 'allotment', location_name = 'North of Catherby')
const L32 = new Patch(location = 'L32', seeds = [], type = 'allotment', location_name = 'North of Catherby')
const L33 = new Patch(location = 'L33', seeds = [], type = 'flower', location_name = 'North of Catherby')
const L34 = new Patch(location = 'L34', seeds = [], type = 'herb', location_name = 'North of Catherby')

//location 4 (North of Ardougne)
const L41 = new Patch(location = 'L41', seeds = [], type = 'allotment', location_name = 'North of Ardougne')
const L42 = new Patch(location = 'L42', seeds = [], type = 'allotment', location_name = 'North of Ardougne')
const L43 = new Patch(location = 'L43', seeds = [], type = 'flower', location_name = 'North of Ardougne')
const L44 = new Patch(location = 'L44', seeds = [], type = 'herb', location_name = 'North of Ardougne')

//location 5 (Southwest corner of Hosidius)
const L51 = new Patch(location = 'L51', seeds = [], type = 'allotment', location_name = 'Southwest corner of Hosidius')
const L52 = new Patch(location = 'L52', seeds = [], type = 'allotment', location_name = 'Southwest corner of Hosidius')
const L53 = new Patch(location = 'L53', seeds = [], type = 'flower', location_name = 'Southwest corner of Hosidius')
const L54 = new Patch(location = 'L54', seeds = [], type = 'herb', location_name = 'Southwest corner of Hosidius')

//Create the player #leet boy
const player = new Player(username = 'Jane Solo', level = 32)

getinventory(patchlist, player);